### ISSUE TITLE
Long Time to Decode GeoJson MultiPolygons with lots of coordinates

### ISSUE THREAD

**Issue by Siggs2000** [rgeo/rgeo-geojson#32] opened 2017-04-07 00:24 UTC
I've run into an issue with decoding multipolygons that contain a really large number of coordinates. I noticed it on one in particular that contained a little over 10k points and it was taking 38 seconds on Heroku. (And the heroku router times out at 30 sec...) 

Is there anything I can do to speed things along? The polygons are are cartesian (not 3d) and used to later query for rgeo points that `st_intersects` (if we could get past this decoding part) 

The polygon in question [can be found and tested here](https://gist.github.com/Siggs2000/be1be56f4e9d1c6760c8311559b28f06)

I'm using this code to decode it: `poly = RGeo::GeoJSON.decode(mp.to_json, :json_parser => :json)`
(`mp` is the geojson multipolygon in the linked gist) and this seems to work without issue for other polygons with fewer points. 

Any and all tips are greatly appreciated!

**Comment by amauryfischer** [comment] 2018-03-21 08:18
Same problem, the parser seems quite slow >_<

**Comment by amauryfischer** [comment] 2018-03-21 09:33
first, i'm not very experienced in programmation ^_^
@teeparham i tried to parse the multipolygon with RGeo::GeoJSON.decode
it takes a long time.
Then i tried to loop into all polygon, use RGeo::GeoJSON.decode on each polygons, and then make a union of them, this was surprisingly fast. (tooks less than 1s)
any idea of what could be the cause ?

**Comment by BuonOmo** [comment] 2020-11-09 18:32
@Siggs2000 the polygon you gave is invalid (it looks like the end has not been saved by github).

Hence for comparison I'll be using [this geojson](https://github.com/gregoiredavid/france-geojson/blob/v2.1.1/metropole-et-outre-mer.geojson) which has roughly the same amount of characters without counting the spaces.

I'm using [`Oj`][oj] as a json parser since it is the fastest by far out there.

Here's the result of my benchmark:

```
                  with geos factory    0.409  (± 0.0%) i/s -      3.000  in   7.328959s
                with simple factory    0.006  (± 0.0%) i/s -      1.000  in 171.116853s
  without the parsing, geos factory    0.402  (± 0.0%) i/s -      3.000  in   7.471688s
without the parsing, simple factory    0.006  (± 0.0%) i/s -      1.000  in 174.939817s
```

So to parse your feature in a decent duration. You should use geos.


So I suggest using [`Oj`][oj] and [`geos`][geos]. For the geos part, you've mentionned usage of `Heroku`. You can use the [buildpack-apt] to have geos on your instances:


```bash
echo 'libgeos-dev=3.7.1-1~pgdg18.04+1' > Aptfile
git add Aptfile
git commit -m "Add Aptfile with libgeos"
heroku buildpacks:add --index 1 heroku-community/apt
git push heroku
heroku run ruby -- -r rgeo -e 'puts "Yeah, geos is correctly installed on Heroku!" if RGeo::Geos.supported?'
``` 

I'll add this to documentation, for sure! I'm closing this issue. If you need more details, you can still write a message here. Or open another issue!

[geos]: https://trac.osgeo.org/geos
[Oj]: https://github.com/ohler55/oj
[buildpack-apt]: https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt

**Closed by BuonOmo** 2020-11-09 18:32 UTC
Labels: documentation
