### ISSUE TITLE
Decode returns empty geometry collection for non-empty geojson

### ISSUE THREAD

**Issue by Jeehut** [rgeo/rgeo-geojson#27] opened 2016-06-29 10:50 UTC
When decoding the geojson from [this OpenStreetMap region](http://polygons.openstreetmap.fr/get_geojson.py?id=62611&params=0) with the following code I receive an empty collection although there's a lot of data:

``` ruby
RGeo::GeoJSON.decode(geojson_string, json_parser: :json)
 => #<RGeo::Geos::CAPIGeometryCollectionImpl:0x3febdfd71198 "GEOMETRYCOLLECTION EMPTY">
```

Would be great to see this fixed! 👍

**Comment by pnull** [comment] 2016-06-29 14:25
Would be cool to have this fixed

**Comment by Dschee** [comment] 2016-07-05 12:02
Just fixed this on the usage side by defining a geo_factory like this:

```
geo_factory = RGeo::Cartesian.simple_factory(srid: 4326)
RGeo::GeoJSON.decode(geojson_string, geo_factory: geo_factory, json_parser: :json)
 => #<RGeo::Cartesian::GeometryCollectionImpl:0x3fc223fdb428 "GEOMETRYCOLLECTION (MULTIPOLYGON (((9.4834096 48.7080301, 9.4834569 48.7079371, ...
```

**Comment by Dschee** [comment] 2016-07-28 10:05
Well, this didn't really solve the problem. I still can't convert the cartesian factory version to a Geos factory which I need though in order to use methods like `contains?`. Here's a rspec test case where I can reproduce the problem:

```ruby
it "reproduces the issue for fetching data via GeoJSON" do
  geojson_data = HTTP.get("http://polygons.openstreetmap.fr/get_geojson.py?id=51477&params=0.010000-0.005000-0.005000").to_s.strip
  geo_factory = ::RGeo::Cartesian.preferred_factory(srid: 4326)
  geom_collection = RGeo::GeoJSON.decode(geojson_data, geo_factory: geo_factory, json_parser: :json)
  germany = geom_collection.first

  %w(62518 191645).map do |osm_id| # Karlsruhe, Dresden
    geojson_data = HTTP.get("http://polygons.openstreetmap.fr/get_geojson.py?id=#{osm_id}&params=0").to_s.strip
    geom_collection = RGeo::GeoJSON.decode(geojson_data, geo_factory: geo_factory, json_parser: :json)
    expect(geom_collection.is_empty?).to be false
  end
end
```

Note that this test includes two regions, one of them (Karlsruhe) working just fine and the other (Dresden) failing. I don't know what the issue is, but it would be great if this could be fixed.

**Comment by superslau** [comment] 2016-08-11 09:13
@Dschee I ran into this same problem using data from Airbnb, and solved it like so:

```ruby
  geo_factory = RGeo::Cartesian.simple_factory(uses_lenient_assertions: true)
  feature_collection = RGeo::GeoJSON.decode(data, json_parser: :json, geo_factory: geo_factory)
```

I have some areas like Chelsea, NY which don't satisfy the validations that rgeo is performing in https://github.com/rgeo/rgeo/blob/master/lib/rgeo/impl_helper/basic_line_string_methods.rb#L135-L137

I'm not actually sure what the end impact of disabling assertions but seems rgeo is overly strict.

The `RGeo::Cartesian::Factory` hides all exceptions interestingly

**Comment by Dschee** [comment] 2016-08-15 21:19
@superslau Thank you for sharing your solution. I will consider adding your solution as a fallback option – broken data should be still better than no data at all. ;)

**Comment by bradcrawford** [comment] 2017-03-15 07:22
I have also been having this problem for the last few hours, oddly it only seems to be areas in the USA that are causing issues (from my limited testing). Here is a sample GeoJSON string that has the problem.

```
geo_json = '{"type":"GeometryCollection","geometries":[{"type":"Polygon","coordinates":[[[237.05947458744052,48.041252095883195],[237.06085324287417,48.04127720225284],[237.0608049631119,48.04223123523302],[237.0605152845383,48.04270107204939],[237.05936729907992,48.042302966321856],[237.0594155788422,48.04168966228833],[237.05947458744052,48.041252095883195]]]}]}'
geometry = RGeo::GeoJSON.decode(geo_json, json_parser: :json, geo_factory: RGeo::Geographic.simple_mercator_factory)

#<RGeo::Geographic::ProjectedGeometryCollectionImpl:0x3fcdcade91bc "GEOMETRYCOLLECTION EMPTY">
```
Anyway, after much hair pulling, I reverted from RGeo 0.6.0 to 0.5.3 and it seems to have fixed it. Geos version is 3.6.1 and Proj version is 4.9.3.

Hopefully this helps someone!

**Comment by BuonOmo** [comment] 2020-11-04 21:51
@Jeehut thanks for the clear and reproducible test ! However, it looks like I'm too late to the party, and now the polygons work.

And it seems like indeed @superslau's solution is the way to go, for now. I'm closing this PR in favor 
of https://github.com/rgeo/rgeo-geojson/issues/33, because they look like the same issue ! If not, please open a new PR 🙂

**Closed by BuonOmo** 2020-11-04 21:51 UTC
Labels: bug

**Comment by Jeehut** [comment] 2020-11-05 08:01
@BuonOmo Thanks for taking a look at this, but since this is 4 years old, I don't even remember which project I came across this problem. But goot to hear that it's probably solved. :)
